export default [
  { name: "HTML", img: "./skills/html.svg" },
  { name: "CSS", img: "./skills/css.svg" },
  { name: "Javascript", img: "./skills/javascript.svg" },
  { name: "Typescript", img: "./skills/typescript.svg" },
  { name: "React", img: "./skills/react.svg" },
  { name: "Next", img: "./skills/next.svg" },
  { name: "NextAuth", img: "./skills/next-auth.svg" },
  { name: "Axios", img: "./skills/canva.svg" },
  { name: "Node", img: "./skills/node.svg" },
  { name: "Prisma", img: "./skills/prisma.svg" },
  { name: "Zod", img: "./skills/zod.svg" },
  { name: "Tailwind", img: "./skills/tailwind.svg" },
  { name: "Bootstrap", img: "./skills/bootstrap.svg" },
  { name: "Git", img: "./skills/git.svg" },
  { name: "Github", img: "./skills/github.svg" },
  { name: "MaterialUI", img: "./skills/materialui.svg" },
  { name: "ShadcnUI", img: "./skills/shadcn.png" },
  { name: "FlowbiteUI", img: "./skills/flowbite.png" },
  { name: "Canva", img: "./skills/axios.png" },
];
